on: pull_request_target

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: Comment on a PR
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Comment PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hi! If you opened this PR to add a new website to the list, please use this link instead: https://github.com/syxanash/awesome-web-desktops/issues/new?&template=1-site-request.yml Thank you for contributing! 🙏
